# Generated by Django 2.1.5 on 2020-12-01 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0007_auto_20181229_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meals',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
