# Generated by Django 2.1.5 on 2020-12-05 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0008_auto_20201201_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meals',
            name='description',
            field=models.TextField(max_length=2000),
        ),
    ]
