# Generated by Django 2.1.5 on 2020-11-24 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0002_auto_20190105_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chef',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
