# Generated by Django 2.1.5 on 2020-11-18 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_auto_20201118_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='Date',
            field=models.DateField(default='2020-11-16'),
        ),
    ]
